app/models.py
from . import db
from werkzeug.security import generate_password_hash,check_password_hash
from flask_login import UserMixin
from . import login_manager



class User(UserMixin,db.Model):
    __tablename__ = 'users'
    id = db.Column(db.Integer,primary_key = True)
    username = db.Column(db.String(255),index=True)
    email = db.Column(db.String(255),unique = True,index=True)
    comment= db.relationship('Comment',backref='user',lazy = "dynamic")
    blog= db.relationship('Blog',backref='user',lazy = "dynamic")
    pass_secure = db.Column(db.String(255))

    @property
    def password(self):
         raise AttributeError('You cannot read the password attribute')
    @password.setter
    def password(self, password):
            self.pass_secure = generate_password_hash(password)


    def verify_password(self,password):
            return check_password_hash(self.pass_secure,password)     

    @login_manager.user_loader
    def load_user(user_id):
        return User.query.get(int(user_id))


    def __repr__(self):
        return f'User {self.username}'



class Blog(db.Model):
        __tablename__= 'blogs'
        id = db.Column(db.Integer,primary_key = True)
        author = db.Column(db.String(255))
        blog =   db.Column(db.String(255))
        user_id = db.Column(db.Integer,db.ForeignKey('users.id'))
        comment = db.relationship('Comment',backref ='blog',lazy="dynamic")
        def save_blog(self):
            db.session.add(self)
            db.session.commit()
        @classmethod
        def get_blog(id):
            blog = Blog.query.order_by(blog_id = id).desc().all()
            return blogs

        def __repr__(self):
            return f'Writer{self.blog}'

class Comment(db.Model):
        __tablename__= 'comments'
        id = db.Column(db.Integer,primary_key = True)
        comment =   db.Column(db.String(255))
        user_id = db.Column(db.Integer,db.ForeignKey('users.id'))
        blog_id = db.Column(db.Integer,db.ForeignKey('blogs.id'))
        
        def save_comment(self):
            db.session.add(self)
            db.session.commit()
        
        def __repr__(Self):
            return f'Comment{self.comment}'

app/main/forms.py
from  flask_wtf import FlaskForm
from wtforms import StringField,SubmitField,BooleanField,TextAreaField
from wtforms.validators import Required
from wtforms import ValidationError

class UpdateProfile(FlaskForm):
    bio = TextAreaField('Tell us about you.',validators = [Required()])
    submit = SubmitField('Submit')

class BlogForm(FlaskForm):
  author = StringField('Author',validators=[Required()])
  blog = TextAreaField('Write a blog',validators=[Required()])
  submit = SubmitField('submit')

class CommentForm(FlaskForm):
  comment = TextAreaField('Your comment here',validators=[Required()])
  author = StringField('Author',validators=[Required()])
  submit = SubmitField('submit')

app/__init__.py
from flask import Flask
from .config import config_options
from flask_sqlalchemy import SQLAlchemy
from flask_bootstrap import Bootstrap
from flask_login import LoginManager
#from flask_uploads import UploadSet,configure_uploads,IMAGES
from flask_mail import Mail

login_manager = LoginManager()
login_manager.session_protection = 'strong'
login_manager.login_view = 'auth.login'

bootstrap = Bootstrap()
db = SQLAlchemy()
#photos = UploadSet('photos',IMAGES)
mail = Mail()

def create_app(config_name):
    app = Flask(__name__)
    bootstrap.init_app(app)
    db.init_app(app)
    mail.init_app(app)
    #configure_uploads(app,photos)
    app.config.from_object(config_options[config_name])
    login_manager.init_app(app)
    from app.auth import auth as auth_blueprint
    app.register_blueprint(auth_blueprint)
    from app.main import main as main_blueprint
    app.register_blueprint(main_blueprint)
    


    return app

app/main/__init__.py
from flask import Blueprint

main = Blueprint('main',__name__)

from . views import *

app/main/views.py
from flask import render_template,request,redirect,url_for,abort
from ..models import User
from flask_login import login_required,current_user
from . import main
from .forms import UpdateProfile,BlogForm,CommentForm
from .. import db
from app.models import Blog,Comment
from ..requests import get_quotes

@main.route('/')
def index():
    quotes = get_quotes()
    print(quotes)
    my_blogs = Blog.query.all()
    print(my_blogs)
    return render_template ('index.html',quotes=quotes,my_blogs=my_blogs)

@main.route('/user/<uname>')
def profile(uname):
    user = User.query.filter_by(username = uname).first()
    if user is None:
        abort(404)
    return render_template("profile/profile.html",user=user)

@main.route('/user/<uname>/update',methods = ['GET','POST'])
@login_required
def update_profile(uname):
    user = User.query.filter_by(username = uname).first()
    if user is None:
        abort(404)

    form = UpdateProfile()

    if form.validate_on_submit():
        user.bio = form.bio.data

        db.session.add(user)
        db.session.commit()

        return redirect(url_for('.profile',uname=user.username))

    return render_template('profile/update.html',form =form)


@main.route('/user/<uname>/update/pic',methods= ['POST'])
@login_required
def update_pic(uname):
    user = User.query.filter_by(username = uname).first()
    if 'photo' in request.files:
        filename = photos.save(request.files['photo'])
        path = f'photos/{filename}'
        user.profile_pic_path = path
        db.session.commit()
    return redirect(url_for('main.profile',uname=uname))

@main.route('/blog',methods=['GET','POST'])
@login_required
def write_blog():
    form1 = BlogForm()
    if form1.validate_on_submit():
        user_id = current_user._get_current_object().id
        blog = Blog(blog =form1.blog.data,user_id=user_id,author= form1.author.data)
        blog.save_blog() 
        return redirect(url_for('main.index'))
    return render_template('blog.html',form1=form1)

@main.route('/comment/<int:blog_id>',methods=['GET','POST']) 
@login_required
def blog_comment(blog_id):
    form2 = CommentForm() 
    comment = Comment.query.filter_by(blog_id=blog_id).all() 
    if form2.validate_on_submit():
        blog_id = blog_id
        user_id = current_user._get_current_object().id
        comment = Comment(comment=form2.comment.data,user_id=user_id,blog_id=blog_id) 
        comment.save_comment()
        return redirect(url_for('main.index'))
    return render_template('comment.html',form2=form2,comment=comment)

app/templates/base.html
<html>
    {% block styles %}
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
    {% endblock %}
    <body>
    {% block navbar %}
    {% include "navbar.html" %}
    {% endblock %}
    
    {% block content %}
    {% endblock %}
    {% block scripts %}
    <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>
    {% endblock %}
    </body>
</html>

app/templates/blog.html
{% extends 'base.html'  %}
{% import 'bootstrap/wtf.html' as wtf%}

{% block styles%}
{{ super() }}
<link rel="stylesheet" href="{{url_for('static',filename='css/index.css')}}">
{% endblock%}

{% block content %}

    <div class="container">
      <div class="card">
            <div class="row">
                    <div class="col-md-2"> </div>
                    <div class="col-md-8">
        
                    {{wtf.quick_form(form1)}}
                    </div>
                    <div class="col-md-2"></div>
                </div>
      </div>
    </div>
{% endblock %}

app/templates/comment.html
{% extends 'base.html'  %}
{% import 'bootstrap/wtf.html' as wtf%}
{% block styles%}
{{ super() }}
<link rel="stylesheet" href="{{url_for('static',filename='css/index.css')}}">
{% endblock%}

{% block content %}

    <div class="container">
        <div class="row">
            <div class="col-md-2"> </div>
            <div class="col-md-8">
            {{wtf.quick_form(form2)}}
            </div>
            <div class="col-md-2"></div>
        </div>
    </div>
    {% for comment in comment %}
    {{comment.comment}}
  {% endfor %}

{% endblock %}

app/templates/index.html
{% extends 'base.html'  %}
{% import 'bootstrap/wtf.html' as wtf%}
{% block styles%}
{{ super() }}
<link rel="stylesheet" href="{{url_for('static',filename='css/index.css')}}">
{% endblock%}

{% block content %}

<body>
    <h1>WELCOME TO PESH BLOGS</h1>
    <div class="container">
        <div class="row">
            <div class="col-md-12">
                <div class="card default-color" style="max-width: 20rem;">
                    <div class="card-body">
                        <blockquote class="blockquote mb-0">
                            <p>{{quotes.quote}}</p><br>
                            <footer class="blockquote-footer">Quote by <cite title="Author">"{{quotes.author}}"</cite>
                            </footer>
                            
                        </blockquote>
                    </div>
                </div>
            </div>
            {% for blogs in my_blogs %}
            <div class="col-md-12">
                <div class="card" style="width: 18rem;">
                    <div class="card-body">
                        <h5 class="card-title">
                            {{blogs.author}}</h5>
                        <p class="card-text">
                            {{blogs.blog}}</p>
                        <a href="{{url_for('main.blog_comment',blog_id=blogs.id)}}" class="btn btn-success">Comment</a>
                    </div>
                </div>

            </div>
        </div>
    </div>
    {% endfor%}
</body>
{% endblock %}

app/templates/navbar.html
<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
    <a class="navbar-brand" href="{{url_for('main.index')}}">Home</a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav mr-auto">
        <li class="nav-item">
          <a class="nav-link" href="#"></a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="/blog">Blog</a>
        </li>
      </ul>
      <ul class="nav navbar-nav navbar-right">
        {% if current_user.is_authenticated %}
        <li><a href="{{url_for('main.profile',uname=current_user.username)}}">Profile</a></li>
        <li><a href="{{url_for('auth.logout')}}">Sign out</a></li>
        {% else %}
        <li><a href="{{url_for('auth.login')}}">Sign in</a></li>
        {%endif%}
      </ul>
  
    </div>
  </nav>

    

    

app/templates/profile/profile.html
{% extends 'base.html'%}

{% block content %}
<div class="container">
<div class="row">
<!-- displaying  Username-->
  <div class="col-md-4">
    <h3> {{user.username| capitalize}} </h3>

    <!--Displaying user bio-->
    {% if user.bio %}
      <p> {{user.bio}}</p>
    {%else%}
      <p> {{user.username| capitalize}} has no bio </p>
    {% endif %}
  </div>
  

  <!--Display profile photo-->
  <div class="col-md-4">

    {% if user.profile_pic_path %}
    <img src="{{url_for('static',filename=user.profile_pic_path)}}" alt="" class="img-thumbnail">
    {%else%}
    <p>No profile picture</p>
    {% endif %}
    {% if user == current_user %}
    <form  action="{{url_for('main.update_pic',uname=user.username)}}" method="post" enctype = "multipart/form-data">

      <input type="file"  name="photo" class="form-control" required>
      <input type="submit">
    </form>
      {% endif %}
  </div>

  


  </div>


</div>
</div>
{% endblock %}

app/templates/profile/update.html
{% extends 'base.html' %}
{% import 'bootstrap/wtf.html' as wtf %}
{% block content %}
<div class="container">
  {{wtf.quick_form(form)}}
</div>
{% endblock %}